/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Challenge message for wallet authentication
*/
export class ChallengeResponse {
    /**
    * Challenge message to sign
    */
    'message'?: string;
    /**
    * Wallet address of the user
    */
    'walletAddress'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletAddress",
            "baseName": "wallet_address",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChallengeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
