/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserBasic } from '../models/UserBasic';
import { HttpFile } from '../http/http';

export class DAO {
    'daoId'?: number;
    'name': string;
    'description': string;
    'ownerId': number;
    'isActive'?: boolean;
    'admins'?: Array<UserBasic>;
    'members'?: Array<UserBasic>;
    'userWhoMadeRequest': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "ownerId",
            "baseName": "owner_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "admins",
            "baseName": "admins",
            "type": "Array<UserBasic>",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<UserBasic>",
            "format": ""
        },
        {
            "name": "userWhoMadeRequest",
            "baseName": "user_who_made_request",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAO.attributeTypeMap;
    }

    public constructor() {
    }
}
