/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Input informations need to create user.
*/
export class InputCreateUser {
    /**
    * Username of the user
    */
    'username'?: string;
    /**
    * Email of the user
    */
    'email'?: string;
    /**
    * Password of the user
    */
    'password'?: string;
    /**
    * Discord username of the user
    */
    'discordUsername'?: string;
    /**
    * Wallet address of the user
    */
    'walletAddress'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "discordUsername",
            "baseName": "discord_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletAddress",
            "baseName": "wallet_address",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InputCreateUser.attributeTypeMap;
    }

    public constructor() {
    }
}
