/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PaginationMetadata {
    'total'?: number;
    'totalPages'?: number;
    'firstPage'?: number;
    'lastPage'?: number;
    'page'?: number;
    'previousPage'?: number;
    'nextPage'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalPages",
            "baseName": "total_pages",
            "type": "number",
            "format": ""
        },
        {
            "name": "firstPage",
            "baseName": "first_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastPage",
            "baseName": "last_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        },
        {
            "name": "previousPage",
            "baseName": "previous_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "nextPage",
            "baseName": "next_page",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaginationMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}
